// <auto-generated />
namespace EduConnect.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class contact2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact2));
        
        string IMigrationMetadata.Id
        {
            get { return "202505271155468_contact2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
